require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GolfersController do

  # This should return the minimal set of attributes required to create a valid
  # Golfer. As you add validations to Golfer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GolfersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all golfers as @golfers" do
      golfer = Golfer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:golfers).should eq([golfer])
    end
  end

  describe "GET show" do
    it "assigns the requested golfer as @golfer" do
      golfer = Golfer.create! valid_attributes
      get :show, {:id => golfer.to_param}, valid_session
      assigns(:golfer).should eq(golfer)
    end
  end

  describe "GET new" do
    it "assigns a new golfer as @golfer" do
      get :new, {}, valid_session
      assigns(:golfer).should be_a_new(Golfer)
    end
  end

  describe "GET edit" do
    it "assigns the requested golfer as @golfer" do
      golfer = Golfer.create! valid_attributes
      get :edit, {:id => golfer.to_param}, valid_session
      assigns(:golfer).should eq(golfer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Golfer" do
        expect {
          post :create, {:golfer => valid_attributes}, valid_session
        }.to change(Golfer, :count).by(1)
      end

      it "assigns a newly created golfer as @golfer" do
        post :create, {:golfer => valid_attributes}, valid_session
        assigns(:golfer).should be_a(Golfer)
        assigns(:golfer).should be_persisted
      end

      it "redirects to the created golfer" do
        post :create, {:golfer => valid_attributes}, valid_session
        response.should redirect_to(Golfer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved golfer as @golfer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Golfer.any_instance.stub(:save).and_return(false)
        post :create, {:golfer => { "first_name" => "invalid value" }}, valid_session
        assigns(:golfer).should be_a_new(Golfer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Golfer.any_instance.stub(:save).and_return(false)
        post :create, {:golfer => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested golfer" do
        golfer = Golfer.create! valid_attributes
        # Assuming there are no other golfers in the database, this
        # specifies that the Golfer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Golfer.any_instance.should_receive(:update_attributes).with({ "first_name" => "MyString" })
        put :update, {:id => golfer.to_param, :golfer => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested golfer as @golfer" do
        golfer = Golfer.create! valid_attributes
        put :update, {:id => golfer.to_param, :golfer => valid_attributes}, valid_session
        assigns(:golfer).should eq(golfer)
      end

      it "redirects to the golfer" do
        golfer = Golfer.create! valid_attributes
        put :update, {:id => golfer.to_param, :golfer => valid_attributes}, valid_session
        response.should redirect_to(golfer)
      end
    end

    describe "with invalid params" do
      it "assigns the golfer as @golfer" do
        golfer = Golfer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Golfer.any_instance.stub(:save).and_return(false)
        put :update, {:id => golfer.to_param, :golfer => { "first_name" => "invalid value" }}, valid_session
        assigns(:golfer).should eq(golfer)
      end

      it "re-renders the 'edit' template" do
        golfer = Golfer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Golfer.any_instance.stub(:save).and_return(false)
        put :update, {:id => golfer.to_param, :golfer => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested golfer" do
      golfer = Golfer.create! valid_attributes
      expect {
        delete :destroy, {:id => golfer.to_param}, valid_session
      }.to change(Golfer, :count).by(-1)
    end

    it "redirects to the golfers list" do
      golfer = Golfer.create! valid_attributes
      delete :destroy, {:id => golfer.to_param}, valid_session
      response.should redirect_to(golfers_url)
    end
  end

end
